name: "On PR creation to main branch"

on:
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.0.8
  GO_VERSION: 1.17.5
  AWS_REGION: "us-east-1"

jobs:
  execute-basic-terraform-checks:
    name: "Execute basic Terraform checks"
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run terraform init
        run: terraform init
        working-directory: ./infrastructure/modules/s3-bucket

      - name: Run terraform fmt check
        run: terraform fmt -check
        working-directory: ./infrastructure/modules/s3-bucket

      - name: Run terraform validate check
        run: terraform validate
        working-directory: ./infrastructure/modules/s3-bucket

  execute-unit-test:
    name: "Execute infrastructure unit test"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs:
      - execute-basic-terraform-checks

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Execute unit test
        run: go test -v example_infrastructure_unit_test.go
        working-directory: ./test

  execute-integration-test:
    name: "Execute infrastructure integration test"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs:
      - execute-unit-test

    env:
      WORKING_DIRECTORY: ./test

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Execute integration test
        run: go test -v example_infrastructure_integration_test.go
        working-directory: ./test
